name: rename_capture
description: "It's a mobile application for taking picture, give a custom name to the picture and save it localy. we call it RenamePicture."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  animated_splash_screen: ^1.3.0
  lottie: ^2.7.0
  dotted_border: ^2.1.0
  image_picker: ^1.1.2
  sqflite: ^2.3.3+1
  path_provider: ^2.1.3
  image_gallery_saver: '^2.0.3'
  permission_handler: ^11.3.1
  device_info_plus: ^9.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.jpeg"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/app_logo.jpeg"

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # assets
  assets:
    - assets/images/
    - assets/animation/

  fonts:
    - family: Lobster
      fonts:
        - asset: assets/fonts/Lobster-Regular.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-medium.ttf
          weight: 400
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-medium.ttf


